;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2017/12/28 16:13:37

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; Atomic www.cssmoban.com模板之家 index\about.html
#define IDH_1001	1001	; Atomic www.cssmoban.com模板之家 index\blog.html
#define IDH_1002	1002	; Atomic www.cssmoban.com模板之家 index\contact.html
#define IDH_1003	1003	; Atomic www.cssmoban.com模板之家 index\support.html
