;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2017/12/28 16:13:37

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=index\about.html	; Atomic www.cssmoban.com模板之家
IDH_1001=index\blog.html	; Atomic www.cssmoban.com模板之家
IDH_1002=index\contact.html	; Atomic www.cssmoban.com模板之家
IDH_1003=index\support.html	; Atomic www.cssmoban.com模板之家
